### ISSUE TITLE
bug in code

### ISSUE THREAD

**Issue by cabouman** [cabouman/mbircone#61]
The demos are crashing. Here are the error messages.

```
Writing System Matrix to /Users/bouman/.cache/mbircone/sysmatrix/177a4edeaeeae185ea3e_pid91062_rndnum957.sysmatrix
Total size written = 4.751521e-03 GB
sino shape =  (144, 200, 128) float32
Traceback (most recent call last):
  File "demo_3D_shepp_logan.py", line 78, in <module>
    recon = mbircone.cone3D.recon(sino, angles,
  File "/usr/local/anaconda3/envs/mbircone/lib/python3.8/site-packages/mbircone/cone3D.py", line 671, in recon
    x = ci.recon_cy(sino, weights, init_image, prox_image,
  File "mbircone/interface_cy_c.pyx", line 319, in mbircone.interface_cy_c.recon_cy
IndexError: Out of bounds on buffer access (axis 0)
```

**Comment by dyang37** [comment]
Fixed in latest commit of "recover" branch
